package com.muhammedessa.controllers;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;

import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet(urlPatterns = "/loginServlet")
public class loginServlet extends HttpServlet{

	@Override
	protected void doGet(HttpServletRequest request,HttpServletResponse response) throws IOException {
		PrintWriter out = response.getWriter();
//		out.println("<!DOCTYPE html>");
//		
//		out.println("<html>");
//		
//		out.println("<head>");
//		out.println("<title>page title </title>");
//		out.println("</head>");
//		out.println("<body>");
//
//		out.println("<h1>This is a Heading</h1>");
//		out.print("<p>This is a paragraph</p>");
//		out.println("</body>");
//		
//		
//		out.println("</html>");
//		
//		
		out.print("<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "<head>\r\n"
				+ "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
				+ "<style>\r\n"
				+ "body {font-family: Arial, Helvetica, sans-serif;}\r\n"
				+ "\r\n"
				+ "/* Full-width input fields */\r\n"
				+ "input[type=text], input[type=password] {\r\n"
				+ "  width: 100%;\r\n"
				+ "  padding: 12px 20px;\r\n"
				+ "  margin: 8px 0;\r\n"
				+ "  display: inline-block;\r\n"
				+ "  border: 1px solid #ccc;\r\n"
				+ "  box-sizing: border-box;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* Set a style for all buttons */\r\n"
				+ "button {\r\n"
				+ "  background-color: #04AA6D;\r\n"
				+ "  color: white;\r\n"
				+ "  padding: 14px 20px;\r\n"
				+ "  margin: 8px 0;\r\n"
				+ "  border: none;\r\n"
				+ "  cursor: pointer;\r\n"
				+ "  width: 100%;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "button:hover {\r\n"
				+ "  opacity: 0.8;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* Extra styles for the cancel button */\r\n"
				+ ".cancelbtn {\r\n"
				+ "  width: auto;\r\n"
				+ "  padding: 10px 18px;\r\n"
				+ "  background-color: #f44336;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* Center the image and position the close button */\r\n"
				+ ".imgcontainer {\r\n"
				+ "  text-align: center;\r\n"
				+ "  margin: 24px 0 12px 0;\r\n"
				+ "  position: relative;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "img.avatar {\r\n"
				+ "  width: 40%;\r\n"
				+ "  border-radius: 50%;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".container {\r\n"
				+ "  padding: 16px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "span.psw {\r\n"
				+ "  float: right;\r\n"
				+ "  padding-top: 16px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* The Modal (background) */\r\n"
				+ ".modal {\r\n"
				+ "  display: none; /* Hidden by default */\r\n"
				+ "  position: fixed; /* Stay in place */\r\n"
				+ "  z-index: 1; /* Sit on top */\r\n"
				+ "  left: 0;\r\n"
				+ "  top: 0;\r\n"
				+ "  width: 100%; /* Full width */\r\n"
				+ "  height: 100%; /* Full height */\r\n"
				+ "  overflow: auto; /* Enable scroll if needed */\r\n"
				+ "  background-color: rgb(0,0,0); /* Fallback color */\r\n"
				+ "  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */\r\n"
				+ "  padding-top: 60px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* Modal Content/Box */\r\n"
				+ ".modal-content {\r\n"
				+ "  background-color: #fefefe;\r\n"
				+ "  margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */\r\n"
				+ "  border: 1px solid #888;\r\n"
				+ "  width: 80%; /* Could be more or less, depending on screen size */\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* The Close Button (x) */\r\n"
				+ ".close {\r\n"
				+ "  position: absolute;\r\n"
				+ "  right: 25px;\r\n"
				+ "  top: 0;\r\n"
				+ "  color: #000;\r\n"
				+ "  font-size: 35px;\r\n"
				+ "  font-weight: bold;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".close:hover,\r\n"
				+ ".close:focus {\r\n"
				+ "  color: red;\r\n"
				+ "  cursor: pointer;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* Add Zoom Animation */\r\n"
				+ ".animate {\r\n"
				+ "  -webkit-animation: animatezoom 0.6s;\r\n"
				+ "  animation: animatezoom 0.6s\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "@-webkit-keyframes animatezoom {\r\n"
				+ "  from {-webkit-transform: scale(0)} \r\n"
				+ "  to {-webkit-transform: scale(1)}\r\n"
				+ "}\r\n"
				+ "  \r\n"
				+ "@keyframes animatezoom {\r\n"
				+ "  from {transform: scale(0)} \r\n"
				+ "  to {transform: scale(1)}\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* Change styles for span and cancel button on extra small screens */\r\n"
				+ "@media screen and (max-width: 300px) {\r\n"
				+ "  span.psw {\r\n"
				+ "     display: block;\r\n"
				+ "     float: none;\r\n"
				+ "  }\r\n"
				+ "  .cancelbtn {\r\n"
				+ "     width: 100%;\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "</style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "\r\n"
				+ "<h2>Modal Login Form</h2>\r\n"
				+ "\r\n"
				+ "<button onclick=\"document.getElementById('id01').style.display='block'\" style=\"width:auto;\">Login</button>\r\n"
				+ "\r\n"
				+ "<div id=\"id01\" class=\"modal\">\r\n"
				+ "  \r\n"
				+ "  <form class=\"modal-content animate\" action=\"/action_page.php\" method=\"post\">\r\n"
				+ "    <div class=\"imgcontainer\">\r\n"
				+ "      <span onclick=\"document.getElementById('id01').style.display='none'\" class=\"close\" title=\"Close Modal\">&times;</span>\r\n"
				+ "      <img src=\"img_avatar2.png\" alt=\"Avatar\" class=\"avatar\">\r\n"
				+ "    </div>\r\n"
				+ "\r\n"
				+ "    <div class=\"container\">\r\n"
				+ "      <label for=\"uname\"><b>Username</b></label>\r\n"
				+ "      <input type=\"text\" placeholder=\"Enter Username\" name=\"uname\" required>\r\n"
				+ "\r\n"
				+ "      <label for=\"psw\"><b>Password</b></label>\r\n"
				+ "      <input type=\"password\" placeholder=\"Enter Password\" name=\"psw\" required>\r\n"
				+ "        \r\n"
				+ "      <button type=\"submit\">Login</button>\r\n"
				+ "      <label>\r\n"
				+ "        <input type=\"checkbox\" checked=\"checked\" name=\"remember\"> Remember me\r\n"
				+ "      </label>\r\n"
				+ "    </div>\r\n"
				+ "\r\n"
				+ "    <div class=\"container\" style=\"background-color:#f1f1f1\">\r\n"
				+ "      <button type=\"button\" onclick=\"document.getElementById('id01').style.display='none'\" class=\"cancelbtn\">Cancel</button>\r\n"
				+ "      <span class=\"psw\">Forgot <a href=\"#\">password?</a></span>\r\n"
				+ "    </div>\r\n"
				+ "  </form>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "<script>\r\n"
				+ "// Get the modal\r\n"
				+ "var modal = document.getElementById('id01');\r\n"
				+ "\r\n"
				+ "// When the user clicks anywhere outside of the modal, close it\r\n"
				+ "window.onclick = function(event) {\r\n"
				+ "    if (event.target == modal) {\r\n"
				+ "        modal.style.display = \"none\";\r\n"
				+ "    }\r\n"
				+ "}\r\n"
				+ "</script>\r\n"
				+ "\r\n"
				+ "</body>\r\n"
				+ "</html>\r\n"
				+ "");
		
	}
    
	
}
